// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>

//! Property-based tests for Kea-Bivouac using proptest.
//!
//! These tests verify that serde round-trips and structural invariants
//! hold for arbitrary input values generated by proptest.

use proptest::prelude::*;
use kea_bivouac::playbook::{Playbook, PlaybookAction, PlaybookTrigger};

// Property test: Any valid cron string in PlaybookTrigger::Schedule serializes correctly
proptest! {
    #[test]
    fn prop_schedule_trigger_roundtrip(cron in r"[0-9*,/-]{5,20}") {
        let trigger = PlaybookTrigger::Schedule {
            cron: cron.clone(),
        };
        let serialized = toml::to_string(&trigger).unwrap();
        let deserialized: PlaybookTrigger = toml::from_str(&serialized).unwrap();
        prop_assert_eq!(trigger, deserialized);
    }
}

// Property test: Any u64 timeout value within reasonable range roundtrips via serde
proptest! {
    #[test]
    fn prop_wait_action_roundtrip(duration in 0u64..86400) {
        let action = PlaybookAction::Wait {
            duration_secs: duration,
        };
        let serialized = toml::to_string(&action).unwrap();
        let deserialized: PlaybookAction = toml::from_str(&serialized).unwrap();
        match (action, deserialized) {
            (
                PlaybookAction::Wait { duration_secs: d1 },
                PlaybookAction::Wait { duration_secs: d2 },
            ) => {
                prop_assert_eq!(d1, d2);
            }
            _ => prop_assert!(false, "Expected Wait action"),
        }
    }
}

// Property test: Any non-empty string name and description in Playbook TOML roundtrip
proptest! {
    #[test]
    fn prop_playbook_name_description_roundtrip(
        name in r#"[a-zA-Z0-9\-_.]{1,50}"#,
        description in r#"[a-zA-Z0-9\-_. ]{1,100}"#,
    ) {
        let toml_content = format!(
            r#"name = "{}"
description = "{}"
continue_on_error = false
timeout_secs = 300

[trigger]
type = "manual"

[[actions]]
type = "log"
level = "info"
message = "Test"
"#,
            name, description
        );

        let path = std::path::Path::new("test.toml");
        let playbook = Playbook::from_toml(&toml_content, path).unwrap();
        prop_assert_eq!(playbook.name, name);
        prop_assert_eq!(playbook.description, description);
    }
}

// Property test: Playbook action Command with arbitrary args roundtrips
proptest! {
    #[test]
    fn prop_command_action_roundtrip(
        cmd in r"[a-z]{1,20}",
        timeout in 0u64..3600,
    ) {
        let action = PlaybookAction::Command {
            command: cmd.clone(),
            args: vec!["arg1".to_string(), "arg2".to_string()],
            timeout_secs: Some(timeout),
        };
        let serialized = toml::to_string(&action).unwrap();
        let deserialized: PlaybookAction = toml::from_str(&serialized).unwrap();
        match (action, deserialized) {
            (
                PlaybookAction::Command { command: c1, args: a1, timeout_secs: t1 },
                PlaybookAction::Command { command: c2, args: a2, timeout_secs: t2 },
            ) => {
                prop_assert_eq!(c1, c2);
                prop_assert_eq!(a1, a2);
                prop_assert_eq!(t1, t2);
            }
            _ => prop_assert!(false, "Expected Command action"),
        }
    }
}

// Property test: Health check failure trigger with arbitrary service name
proptest! {
    #[test]
    fn prop_health_check_trigger_roundtrip(
        service in r"[a-z0-9\-]{1,30}"
    ) {
        let trigger = PlaybookTrigger::HealthCheckFailure {
            service: service.clone(),
        };
        let serialized = toml::to_string(&trigger).unwrap();
        let deserialized: PlaybookTrigger = toml::from_str(&serialized).unwrap();
        prop_assert_eq!(trigger, deserialized);
    }
}
